# Generated by Django 4.2.14 on 2024-07-25 10:20

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=auth_app.models.profile_avatar_directory_path),
        ),
    ]
